### ISSUE TITLE
lgf_KeywordHighlightTexts  没这东西吧

### ISSUE THREAD

**Issue by Observer-jin** [aiononhiii/LGFFreePT#1]

**Comment by aiononhiii** [comment]
新建一个 UITextView 分类加入这个方法，或者cocoa pods pod 一下

#pragma mark - 多个关键字高亮
/**
 @param texts 高亮关键字数组
 */
- (void)lgf_KeywordHighlightTexts:(NSArray *)texts;

- (void)lgf_KeywordHighlightTexts:(NSArray *)texts {
    // 获取关键字的位置
    NSArray *ranges = [self rangeOfSubString:texts inString:self.text];
    // 转换成可以操作的字符串类型.
    NSMutableAttributedString *attribute = [[NSMutableAttributedString alloc] initWithString:self.text];
    [attribute addAttribute:NSForegroundColorAttributeName value:self.textColor range:[self.text rangeOfString:self.text]];
    [attribute addAttribute:NSFontAttributeName value:self.font range:[self.text rangeOfString:self.text]];
    [ranges enumerateObjectsUsingBlock:^(NSDictionary *  _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
        // 添加属性(粗体)
        [attribute addAttribute:NSFontAttributeName value:self.font range:[obj[@"range"] rangeValue]];
        // 关键字高亮
        [attribute addAttribute:NSForegroundColorAttributeName value:lgf_HexColor(obj[@"color"]) range:[obj[@"range"] rangeValue]];
    }];
    // 将带属性的字符串添加到cell.textLabel上.
    [self setAttributedText:attribute];
}

- (NSArray*)rangeOfSubString:(NSArray *)texts inString:(NSString*)string {
    NSMutableArray *rangeArray = [NSMutableArray array];
    [texts enumerateObjectsUsingBlock:^(NSDictionary *  _Nonnull subStrDict, NSUInteger idx, BOOL * _Nonnull stop) {
        NSString *subStr = subStrDict[@"text"];
        NSString *string1 = [string stringByAppendingString:subStr];
        
        //
        NSString *temp;
        for(int i = 0; i < string.length; i ++) {
            temp = [string1 substringWithRange:NSMakeRange(i, subStr.length)];
            if ([temp isEqualToString:subStr]) {
                NSRange range = {i, subStr.length};
                [rangeArray addObject:@{@"range" : [NSValue valueWithRange:range], @"color" : subStrDict[@"color"]}];
            }
        }
        // @""字符串高亮
        if ([subStr isEqualToString:@"@(\"([^\"]*)\")"]) {
            NSError *error = nil;
            NSRegularExpression *regularExp = [[NSRegularExpression alloc] initWithPattern:subStr options:NSRegularExpressionCaseInsensitive error:&error];
            [regularExp enumerateMatchesInString:self.text options:NSMatchingReportProgress range:NSMakeRange(0, self.text.length) usingBlock:^(NSTextCheckingResult * _Nullable result, NSMatchingFlags flags, BOOL * _Nonnull stop) {
                if (result) {
                    [rangeArray addObject:@{@"range" : [NSValue valueWithRange:result.range], @"color" : subStrDict[@"color"]}];
                }
            }];
        }
        
    }];
    return rangeArray;
}

**Comment by aiononhiii** [comment]
重新下载一个试试
