### ISSUE TITLE
淘宝页面点击事件

### ISSUE THREAD

**Issue by youcaihuaF** [aiononhiii/LGFFreePT#3]
淘宝上面的截图 添加个button，加个点击事件就不能上下滚动了。请问下 这个怎么处理

**Comment by aiononhiii** [comment]
正常情况下，滚动列表不建议添加 UIButton, 因为 UIButton 内部封装的手势事件比较复杂容易产生冲突，可以使用 UIView/UILabel 添加 tap 点击事件试试
